version: '3.3'

services:
  redis:
    container_name: cache-server
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /.:/root/redis
    environment:
      - REDIS_PORT=6379
    networks:
      - app-net
  
  postgres:
    container_name: sql-server
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /.:/root/postgres
      - postgres_data:/var/lib/postgresql/data/
      - ~/main.sql:/docker-entrypoint-initdb.d/main.sql
    environment:
      - POSTGRES_DB=mainserver
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    networks:
      - app-net

  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    networks:
      - kafka-net
      - app-net
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    networks:
      - kafka-net
      - app-net
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LOG_RETENTION_HOURS=6
    depends_on:
      - zookeeper
      
  app:
    image: 'modelapp'
    container_name: modelapp
    ports:
     - 8081:8081
     - 8090:8090
    networks:
      - app-net

volumes:
  postgres_data:

networks:
  kafka-net:
    driver: bridge
  app-net:
    driver: bridge