apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/docker-app-net: "true"
        io.kompose.service: redis
    spec:
      containers:
        - env:
            - name: REDIS_PORT
              value: "6379"
          image: redis:latest
          name: cache-server
          ports:
            - containerPort: 6379
              hostPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: /root/redis
              name: redis-claim0
      restartPolicy: Always
      volumes:
        - name: redis-claim0
          persistentVolumeClaim:
            claimName: redis-claim0
